/**
 * Pinned kernel clauses — the immutable core of the Stock HQ ruleset.
 *
 * This constant lives in the DEPLOYED BUNDLE, never in the database: a rule version
 * stored in Postgres can be rewritten by an agent, this file cannot. Changing a kernel
 * clause therefore requires a human commit + deploy.
 *
 * GENERATED by `npx tsx scripts/print-kernel-hashes.ts --emit` — do not hand-edit;
 * edit the fenced region in /prompts and regenerate.
 */
export type KernelClause = {
  id: string;
  /** sha256 hex of canonicaliseRegion(text between the BEGIN/END markers). */
  sha256: string;
  /** Canonical text at pin time — kept for diagnostics / diffing a tampered region. */
  canonicalText: string;
};

export const KERNEL_CLAUSES: readonly KernelClause[] = [
  {
    id: "audit-append-only",
    sha256: "9190b16d3510755a3f3a145c5b8248bddc7b8b177c17310142b90bbd91a57be5",
    canonicalText: "## 19. Audit log is append-only (kernel)\n\n- `EvolutionEvent` records are append-only: once written they are never updated, deleted,\n  redacted, back-dated, or rewritten by any agent, routine, or rule version.\n- Any proposal, tool call, or rule change that attempts to modify or remove audit rows is\n  rejected outright, and the rejection is itself appended to the log.\n- Corrections are made by appending a new event that references the earlier one — never by\n  editing history.",
  },
  {
    id: "execution-boundary",
    sha256: "2f4002dccdd1727a3bf4f6b9188f4dd3f3ec308472af1398c3e9918eb1aa2201",
    canonicalText: "## 5. Execution boundary — non-negotiable\n\n- Never place, execute, route, schedule, or simulate a real trade. Never imply one\n  happened. All real-money execution is Ivan's, in his own broker.\n- A BUY signal is a **suggestion**. It must never move a name into the portfolio. A stock\n  enters `list_portfolio` only when Ivan reports an actual trade via `log_trade`.\n- Never auto-add to Portfolio via any tool.",
  },
  {
    id: "fitness-definition",
    sha256: "b93654950853226d9cd9c95997c91ee3b795b61a993eadf9aa78a41e87977fe2",
    canonicalText: "## 17. Fitness definition (kernel)\n\nBranch fitness over a comparison window is exactly:\n\n`fitness = shadowReturn + avoidedLossCredit − drawdownPenalty − turnoverCost − benchmarkReturn`\n\n- All five components are fractions of starting capital (`0.08` = 8%), never percentage points.\n- `shadowReturn` is the branch's paper-ledger return; `benchmarkReturn` is CSPX over the same window.\n- `avoidedLossCredit` is **signed**: correctly avoided losses add, wrongly avoided gains subtract.\n- `drawdownPenalty` and `turnoverCost` are always subtracted, never floored away.\n- No rule change may redefine, reweight, clamp, or drop any component, or swap the benchmark.",
  },
  {
    id: "price-provenance",
    sha256: "f5db05600750c1773efca2a76e74f4639100488906c90e86ff99c401629a91f8",
    canonicalText: "## 3. Price provenance (§12.10-C — supersedes the voided §12.10)\n\nThe sync runs ~06:00 MYT ≈ 18:00 ET, ~2h after the US close. The Daily routine runs\n~08:00 MYT ≈ 20:00 ET. Therefore `currentPrice` values **are final closing prices** of the\njust-completed session — label them \"US close (date)\" with confidence, do not hedge as\n\"intraday\".\n\n- **Stale-sync check:** compare each position/watchlist row's `lastPriceUpdate` and\n  `priceStatus` (from context or `list_portfolio` / `list_watchlist`) to the last\n  completed US session (respecting holidays/weekends). Flag `STALE SYNC` / treat\n  `priceStatus=STALE` or `SYNC_FAILED` as non-actionable marks.\n- **Block recommendations on bad marks:** do **not** issue BUY / ADD / EXIT / REDUCE /\n  RESET STOP / zone-hit recommendations that depend on `currentPrice` when\n  `priceStatus` is `SYNC_FAILED`, `STALE`, or `UNKNOWN` for that ticker. Flag the data\n  issue, reason from the last known-good close if available, and wait for a clean sync.\n  Narrative HOLD/WATCH commentary is fine; size-changing or stop-changing calls are not.\n- The system sees one price per session. Intraday wicks are invisible by design — all\n  stop/zone/trigger evaluations are made on closing prices.\n- Ideas `currentPrice` is **unreliable** unless `priceReliable: true` (requires\n  `leadTicker`). Do not quote unreliable idea prices. §11.4 sanity rules apply: never write\n  one price for a basket; if a value differs >50% from the previous stored value or doesn't\n  plausibly match the lead ticker, flag rather than use.",
  },
  {
    id: "reversion-mechanism",
    sha256: "13316d4b2bd520212acf54a9ccbe1a3d8e485abe9f044a588cb44d50a4d83c17",
    canonicalText: "## 18. Reversion mechanism (kernel)\n\n- Any branch whose equity closes **25% or more below its own high-water mark** hard-reverts\n  immediately: the branch stops trading, its candidate rules are killed, and LIVE returns to\n  the last known-good ACTIVE version.\n- Reversion is evaluated first and takes precedence over every other signal — a breach reverts\n  even when fitness, promotion criteria, or a pending proposal say otherwise.\n- Reversion is never deferred, sampled, overridden by fresh evidence, or waived for \"one more\n  session\".\n- The 25% threshold and this precedence order can only change by a human commit to this file.",
  },
];
