-- Extend Theme for unmapped Notion/trend labels (option A).
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'BIOTECH_GLP1';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'ENERGY_COMMODITIES';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'MARITIME_SHIPBUILDING';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'QUANTUM';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'PREDICTION_MARKETS';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'MACRO';
ALTER TYPE "Theme" ADD VALUE IF NOT EXISTS 'CRITICAL_MINERALS';
