/**
 * Print {id, sha256} for every kernel-fenced region in /prompts.
 * Run after a legitimate human edit to a fenced region, then paste the output into
 * src/lib/rules/kernelClauses.ts.
 *
 * Usage: npx tsx scripts/print-kernel-hashes.ts [--emit] > /dev/null
 *   --emit rewrites src/lib/rules/kernelClauses.ts in place.
 */
import { promises as fs } from "node:fs";
import path from "node:path";
import { canonicaliseRegion, extractRegions, sha256Hex } from "../src/lib/rules/kernel";

const PROMPT_NAMES = ["_shared", "daily", "weekly", "earnings", "monthly"] as const;

async function readPromptFiles(): Promise<Record<string, string>> {
  const dir = path.join(process.cwd(), "prompts");
  const entries = await Promise.all(
    PROMPT_NAMES.map(async (name) => {
      const file = `${name}.md`;
      return [file, await fs.readFile(path.join(dir, file), "utf8")] as const;
    }),
  );
  return Object.fromEntries(entries);
}

function tsLiteral(text: string): string {
  return JSON.stringify(text);
}

async function main() {
  const files = await readPromptFiles();
  const { regions, tampered } = extractRegions(files);

  if (tampered.length > 0) {
    console.error("Malformed kernel markers:", tampered);
    process.exitCode = 1;
    return;
  }

  const clauses = regions
    .map((r) => {
      const canonicalText = canonicaliseRegion(r.text);
      return { id: r.clauseId, sha256: sha256Hex(canonicalText), canonicalText, file: r.file };
    })
    .sort((a, b) => a.id.localeCompare(b.id));

  console.log(
    JSON.stringify(
      clauses.map(({ id, sha256, file }) => ({ id, sha256, file })),
      null,
      2,
    ),
  );

  if (!process.argv.includes("--emit")) return;

  const header = `/**
 * Pinned kernel clauses — the immutable core of the Stock HQ ruleset.
 *
 * This constant lives in the DEPLOYED BUNDLE, never in the database: a rule version
 * stored in Postgres can be rewritten by an agent, this file cannot. Changing a kernel
 * clause therefore requires a human commit + deploy.
 *
 * GENERATED by \`npx tsx scripts/print-kernel-hashes.ts --emit\` — do not hand-edit;
 * edit the fenced region in /prompts and regenerate.
 */
export type KernelClause = {
  id: string;
  /** sha256 hex of canonicaliseRegion(text between the BEGIN/END markers). */
  sha256: string;
  /** Canonical text at pin time — kept for diagnostics / diffing a tampered region. */
  canonicalText: string;
};

export const KERNEL_CLAUSES: readonly KernelClause[] = [
`;
  const body = clauses
    .map(
      (c) =>
        `  {\n    id: ${tsLiteral(c.id)},\n    sha256: ${tsLiteral(c.sha256)},\n    canonicalText: ${tsLiteral(c.canonicalText)},\n  },\n`,
    )
    .join("");
  const out = `${header}${body}];\n`;
  const target = path.join(process.cwd(), "src/lib/rules/kernelClauses.ts");
  await fs.writeFile(target, out, "utf8");
  console.error(`wrote ${target} (${clauses.length} clauses)`);
}

main().catch((err) => {
  console.error(err);
  process.exitCode = 1;
});
